// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: hello.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MyzoneReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Myzonername string `protobuf:"bytes,1,opt,name=myzonername,proto3" json:"myzonername,omitempty"`
}

func (x *MyzoneReq) Reset() {
	*x = MyzoneReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hello_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyzoneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyzoneReq) ProtoMessage() {}

func (x *MyzoneReq) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyzoneReq.ProtoReflect.Descriptor instead.
func (*MyzoneReq) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{0}
}

func (x *MyzoneReq) GetMyzonername() string {
	if x != nil {
		return x.Myzonername
	}
	return ""
}

type MyzoneResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Myzonermessage string `protobuf:"bytes,1,opt,name=myzonermessage,proto3" json:"myzonermessage,omitempty"`
}

func (x *MyzoneResp) Reset() {
	*x = MyzoneResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hello_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyzoneResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyzoneResp) ProtoMessage() {}

func (x *MyzoneResp) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyzoneResp.ProtoReflect.Descriptor instead.
func (*MyzoneResp) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{1}
}

func (x *MyzoneResp) GetMyzonermessage() string {
	if x != nil {
		return x.Myzonermessage
	}
	return ""
}

var File_hello_proto protoreflect.FileDescriptor

var file_hello_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0x2d, 0x0a, 0x09, 0x4d, 0x79, 0x7a, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12, 0x20,
	0x0a, 0x0b, 0x6d, 0x79, 0x7a, 0x6f, 0x6e, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x79, 0x7a, 0x6f, 0x6e, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x34, 0x0a, 0x0a, 0x4d, 0x79, 0x7a, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26,
	0x0a, 0x0e, 0x6d, 0x79, 0x7a, 0x6f, 0x6e, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x79, 0x7a, 0x6f, 0x6e, 0x65, 0x72, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x36, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x4d, 0x79, 0x66, 0x69, 0x72, 0x73, 0x74, 0x12, 0x0d, 0x2e,
	0x70, 0x62, 0x2e, 0x4d, 0x79, 0x7a, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x70,
	0x62, 0x2e, 0x4d, 0x79, 0x7a, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hello_proto_rawDescOnce sync.Once
	file_hello_proto_rawDescData = file_hello_proto_rawDesc
)

func file_hello_proto_rawDescGZIP() []byte {
	file_hello_proto_rawDescOnce.Do(func() {
		file_hello_proto_rawDescData = protoimpl.X.CompressGZIP(file_hello_proto_rawDescData)
	})
	return file_hello_proto_rawDescData
}

var file_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hello_proto_goTypes = []interface{}{
	(*MyzoneReq)(nil),  // 0: pb.MyzoneReq
	(*MyzoneResp)(nil), // 1: pb.MyzoneResp
}
var file_hello_proto_depIdxs = []int32{
	0, // 0: pb.Response.Myfirst:input_type -> pb.MyzoneReq
	1, // 1: pb.Response.Myfirst:output_type -> pb.MyzoneResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hello_proto_init() }
func file_hello_proto_init() {
	if File_hello_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hello_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyzoneReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hello_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyzoneResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hello_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hello_proto_goTypes,
		DependencyIndexes: file_hello_proto_depIdxs,
		MessageInfos:      file_hello_proto_msgTypes,
	}.Build()
	File_hello_proto = out.File
	file_hello_proto_rawDesc = nil
	file_hello_proto_goTypes = nil
	file_hello_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ResponseClient is the client API for Response service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResponseClient interface {
	Myfirst(ctx context.Context, in *MyzoneReq, opts ...grpc.CallOption) (*MyzoneResp, error)
}

type responseClient struct {
	cc grpc.ClientConnInterface
}

func NewResponseClient(cc grpc.ClientConnInterface) ResponseClient {
	return &responseClient{cc}
}

func (c *responseClient) Myfirst(ctx context.Context, in *MyzoneReq, opts ...grpc.CallOption) (*MyzoneResp, error) {
	out := new(MyzoneResp)
	err := c.cc.Invoke(ctx, "/pb.Response/Myfirst", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResponseServer is the server API for Response service.
type ResponseServer interface {
	Myfirst(context.Context, *MyzoneReq) (*MyzoneResp, error)
}

// UnimplementedResponseServer can be embedded to have forward compatible implementations.
type UnimplementedResponseServer struct {
}

func (*UnimplementedResponseServer) Myfirst(context.Context, *MyzoneReq) (*MyzoneResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Myfirst not implemented")
}

func RegisterResponseServer(s *grpc.Server, srv ResponseServer) {
	s.RegisterService(&_Response_serviceDesc, srv)
}

func _Response_Myfirst_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MyzoneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResponseServer).Myfirst(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Response/Myfirst",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResponseServer).Myfirst(ctx, req.(*MyzoneReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Response_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Response",
	HandlerType: (*ResponseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Myfirst",
			Handler:    _Response_Myfirst_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
