// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package hello

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ZoneRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneRequest) Reset()         { *m = ZoneRequest{} }
func (m *ZoneRequest) String() string { return proto.CompactTextString(m) }
func (*ZoneRequest) ProtoMessage()    {}
func (*ZoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0}
}

func (m *ZoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneRequest.Unmarshal(m, b)
}
func (m *ZoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneRequest.Marshal(b, m, deterministic)
}
func (m *ZoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneRequest.Merge(m, src)
}
func (m *ZoneRequest) XXX_Size() int {
	return xxx_messageInfo_ZoneRequest.Size(m)
}
func (m *ZoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneRequest proto.InternalMessageInfo

func (m *ZoneRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ZoneResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hobby                []string `protobuf:"bytes,2,rep,name=hobby,proto3" json:"hobby,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneResponse) Reset()         { *m = ZoneResponse{} }
func (m *ZoneResponse) String() string { return proto.CompactTextString(m) }
func (*ZoneResponse) ProtoMessage()    {}
func (*ZoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1}
}

func (m *ZoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneResponse.Unmarshal(m, b)
}
func (m *ZoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneResponse.Marshal(b, m, deterministic)
}
func (m *ZoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneResponse.Merge(m, src)
}
func (m *ZoneResponse) XXX_Size() int {
	return xxx_messageInfo_ZoneResponse.Size(m)
}
func (m *ZoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneResponse proto.InternalMessageInfo

func (m *ZoneResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ZoneResponse) GetHobby() []string {
	if m != nil {
		return m.Hobby
	}
	return nil
}

func init() {
	proto.RegisterType((*ZoneRequest)(nil), "ZoneRequest")
	proto.RegisterType((*ZoneResponse)(nil), "ZoneResponse")
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_61ef911816e0a8ce) }

var fileDescriptor_61ef911816e0a8ce = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe4, 0xe2, 0x8e, 0xca, 0xcf, 0x4b, 0x0d,
	0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x2c, 0xb8, 0x78, 0x20, 0x4a, 0x8a, 0x0b, 0xf2,
	0xf3, 0x8a, 0x53, 0xb1, 0xa9, 0x11, 0x12, 0xe1, 0x62, 0xcd, 0xc8, 0x4f, 0x4a, 0xaa, 0x94, 0x60,
	0x52, 0x60, 0xd6, 0xe0, 0x0c, 0x82, 0x70, 0x8c, 0xcc, 0xb8, 0x78, 0x41, 0x3a, 0x3d, 0xf3, 0x4a,
	0x52, 0x8b, 0xd2, 0x12, 0x93, 0x53, 0x85, 0x54, 0xb9, 0x58, 0xaa, 0xf2, 0xf3, 0x52, 0x85, 0x78,
	0xf4, 0x90, 0x2c, 0x95, 0xe2, 0xd5, 0x43, 0x36, 0x5f, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x36, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xae, 0x39, 0x49, 0x90, 0xaa, 0x00, 0x00, 0x00,
}
