package main

import (
	"encoding/json"
	"fmt"
)

type Etudent struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
	Pan  []int  `json:"pan"`
}

type AutoGenerated struct {
	Age   int    `json:"age"`
	Name  string `json:"name"`
	Child []int  `json:"child"`
}

func main() {
	test1 := `{ "name": "test" ,"age" : 18 , "pan":[1,2,3,3,5]}`
	a := Etudent{}
	json.Unmarshal([]byte(test1), &a)
	aa := a.Pan
	fmt.Println(&aa, aa, len(aa), cap(aa))
	fmt.Printf("%p\n", aa)
	fmt.Printf("%p\n", a.Pan)
	test2 := `{ "name": "test1" ,"age" : 18 , "pan":[33,44]}`
	json.Unmarshal([]byte(test2), &a)
	fmt.Printf("pointer:%p\n", a.Pan)
	fmt.Println(a.Pan, len(a.Pan), cap(a.Pan))
	//fmt.Println(&aa,aa, len(aa),cap(aa))
	fmt.Printf("%p\n", aa)
	fmt.Println(aa, len(aa), cap(aa))

}
